# Generated by Django 4.1.8 on 2023-04-19 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_tag_post_dislikes_post_likes_post_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="tags",),
        migrations.DeleteModel(name="Tag",),
    ]
