# Generated by Django 4.1.8 on 2023-04-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_tags"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="tags",),
        migrations.DeleteModel(name="Tag",),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
