# Generated by Django 4.1.8 on 2023-04-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_post_tags_delete_tag_post_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(model_name="post", name="tags",),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="post_tags", to="blog.tag"),
        ),
    ]
