# Generated by Django 4.1.8 on 2023-04-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_tag_remove_post_tags_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="post_tags", to="blog.tag"
            ),
        ),
    ]
