# Generated by Django 4.1.8 on 2023-05-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="post_tags", to="blog.tag"),
        ),
    ]
