# Generated by Django 4.1.8 on 2023-05-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
